name: Deploy CI

on:
  push:
    branches: [ master ]
    paths:
    - 'functions/**'

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
    - name: Clone Repo
      uses: actions/checkout@v3
    - name: set up Node 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install firebase tool to global
      run: npm install -g firebase-tools
    - name: Clean install project dependencies
      run: npm clean-install --prefix ./functions
    - name: Deploy to cloud
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.FIREBASE_TOKEN }}
      run: firebase deploy